### ISSUE TITLE
veil

### ISSUE THREAD

**Issue by DjarDjar** [josu22/scripts#1]
Hello I saw your issue in the github for Veil did you find a solution? Because I had the same issue and I didn't really find anything in Google to solve it.

**Comment by josu22** [comment]
> 
> 
> Hello I saw your issue in the github for Veil did you find a solution? Because I had the same issue and I didn't really find anything in Google to solve it.

Hi,

Finally i did not fix that, i have the same problem, if you find some solution, please tell me when you find it, i dont know why the veil-framework developer, just close the issue.

Thanks.

**Comment by DjarDjar** [comment]
okay, I actually found a way that works for me. But can you first tell me an other way that we can contact because Gmail sucks (discord, Twitter, Facebook etc.)?-------- Original Message --------Subject: Re: [josu22/scripts] veil (#1)From: Zero22 To: josu22/scripts CC: DjarDjar ,Author 
Hello I saw your issue in the github for Veil did you find a solution? Because I had the same issue and I didn't really find anything in Google to solve it.

Hi,
Finally i did not fix that, i have the same problem, if you find some solution, please tell me when you find it, i dont know why the veil-framework developer, just close the issue.
Thanks.

**Comment by josu22** [comment]
> 
> okay, I actually found a way that works for me. But can you first tell me an other way that we can contact because Gmail sucks (discord, Twitter, Facebook etc.)?-------- Original Message --------Subject: Re: [josu22/scripts] veil (#1)From: Zero22 To: josu22/scripts CC: DjarDjar ,Author Hello I saw your issue in the github for Veil did you find a solution? Because I had the same issue and I didn't really find anything in Google to solve it. Hi, Finally i did not fix that, i have the same problem, if you find some solution, please tell me when you find it, i dont know why the veil-framework developer, just close the issue. Thanks. —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


@zerox2203 at twitter. Thanks man

**Comment by DjarDjar** [comment]
Okay so did you try ./Veil.py (or "python Veil.py" depending on what python version you have) -setup?

**Comment by DjarDjar** [comment]
You could also use "python3 Veil.py". Sometimes when you have python 2 and
3 install on Kali it could get confused when it comes to choosing the
python version 😀.
